### ISSUE TITLE
Add operator to execute command and capture stdout without showing the command itself

### ISSUE THREAD

**Issue by aryairani** [kowainik/shellmet#17]
`($|)` + `($^)` = `($^|)` ? :)

**Comment by chshersh** [comment]
@aryairani can you elaborate more on your issue? The `$|` operator already executes a shell command and captures the stdout without showing the command itself.

**Comment by aryairani** [comment]
Sorry @chshersh, I was using a mix of `"cmd" [args]` and `"cmd" $| [args]` and just assumed that $| was showing the command as well.
